name: Deploy to My website
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Here is the deployment action
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@v2
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          delete: "true"
          max_retries: "7"
          ftp_ssl_allow: "true"
          ssl_verify_certificate: "true"
          ssl_check_hostname: "false"
          lftp_settings: "set cache:cache-empty-listings true; set cmd:status-interval 1s; set http:user-agent 'firefox';"
          exclude: "*.map,node_modules/**,.git/**"
          exclude_delete: "*.log"
